/**
 *
 * This file is part of Disco.
 *
 * Disco is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Disco is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Disco.  If not, see <http://www.gnu.org/licenses/>.
 */
/**
 *
 * This file is part of Disco.
 *
 * Disco is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * Disco is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Disco. If not, see <http://www.gnu.org/licenses/>.
 */


package eu.diversify.disco.cloudml;

import eu.diversify.disco.controller.problem.Solution;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class Gui extends javax.swing.JFrame implements ControllerListener {

    private static final long serialVersionUID = 1L;
    private final DiversityController controller;

    public Gui(DiversityController controller) {
        initComponents();
        this.controller = controller;
        this.controller.addListener(this);
    }

    private double getSetPoint() {
        return this.setPoint.getValue() / 100D;
    }

    public void setFileToLoad(String file) {
        this.fileToLoad.setText(file);
        loadModel();
    }

    public void setReference(double reference) {
        this.setPoint.setValue((int) Math.round(reference * 100));
    }

    @Override
    public void onSolution(Solution solution) {
        setReference(solution.getDiversity());
        console.append("\n-----\n");
        console.append(solution.toString());
        this.repaint();
    }

    @Override
    public void onVisualisation(DiversityController context) {
        final String fileName = context.getFileNameWithExtension(".png");
        BufferedImage image = null;
        try {
            image = ImageIO.read(new File(fileName));
        } catch (IOException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedImage resizedImage = resize(image, visualisation.getWidth(), visualisation.getHeight(), true);//resize the image to 100x100
        ImageIcon icon = new ImageIcon(resizedImage);
        icon.getImage().flush();
        visualisation.setText("");
        visualisation.setIcon(icon);
        this.repaint();
    }

    // FIXME: to move in a proper place 
    public static BufferedImage resize(BufferedImage image, int width, int height, boolean keepAspectRatio) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        // Keep the aspect ratio:
        if (keepAspectRatio) {
            height = (int) (image.getHeight() * (width * 1D / image.getWidth()));
        }
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPoint = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        fileToLoad = new javax.swing.JTextField();
        chooseModel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        container = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visualisation = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Disco v0.1 - Diversity Controller for CloudML models");

        setPoint.setMajorTickSpacing(10);
        setPoint.setMinorTickSpacing(1);
        setPoint.setOrientation(javax.swing.JSlider.VERTICAL);
        setPoint.setPaintLabels(true);
        setPoint.setPaintTicks(true);
        setPoint.setSnapToTicks(true);
        setPoint.setBorder(javax.swing.BorderFactory.createTitledBorder("Diversity (%) :"));
        setPoint.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("CloudML model:");

        fileToLoad.setText("c:\\Users\\franckc\\mdms.json");
        fileToLoad.setToolTipText("path to the CloudML model you want to load");
        fileToLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileToLoadUpdated(evt);
            }
        });

        chooseModel.setText("Choose");
        chooseModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleChooseButtonPressed(evt);
            }
        });

        console.setEditable(false);
        console.setBackground(new java.awt.Color(240, 240, 240));
        console.setColumns(20);
        console.setRows(5);
        console.setBorder(javax.swing.BorderFactory.createTitledBorder("Controller output"));
        jScrollPane2.setViewportView(console);

        container.setBorder(javax.swing.BorderFactory.createTitledBorder("Deployment Overview:"));

        visualisation.setText("No model loaded");
        jScrollPane1.setViewportView(visualisation);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(setPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 1, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileToLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseModel)
                                .addGap(0, 236, Short.MAX_VALUE))
                            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileToLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseModel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(setPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handleChooseButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleChooseButtonPressed
        JFileChooser chooser = new JFileChooser();
        final int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            final String fileName = chooser.getSelectedFile().getAbsolutePath();
            fileToLoad.setText(fileName);
            loadModel();
       }
    }//GEN-LAST:event_handleChooseButtonPressed

    private void fileToLoadUpdated(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileToLoadUpdated
        loadModel();
    }//GEN-LAST:event_fileToLoadUpdated

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            controller.setDiversity(getSetPoint());
            
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,
                                          ex.getMessage(),
                                          "Error while accessing the selected model",
                                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseModel;
    private javax.swing.JTextArea console;
    private javax.swing.JPanel container;
    private javax.swing.JTextField fileToLoad;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider setPoint;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel visualisation;
    // End of variables declaration//GEN-END:variables

    private void loadModel() throws HeadlessException {
        try {
            this.controller.loadDeployment(fileToLoad.getText());

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,
                                          ex.getMessage(),
                                          "Unable to load the given deployment model!",
                                          JOptionPane.ERROR_MESSAGE);

        }
    }
}
